import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import siadSidebar from "./docs/api/siad/sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'informe-definicion',
    {
      type: "category",
      label: "Análisis",
      items: [
        {
          type: 'autogenerated',
          dirName: 'analisis'
        }
      ]
    },
    {
      type: "category",
      label: "Diseño",
      items: [
        {
          type: 'autogenerated',
          dirName: 'diseno'
        }
      ]
    }
  ],
  apisiad: [
    {
      type: "category",
      label: "SIAD",
      link: {
        type: "generated-index",
        title: "SIAD API",
        description: "Explora los endpoints de la API del Sistema de Asignación de Especialistas (SIAD).",
        slug: "/category/siad-api",
      },
      items: siadSidebar,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
